#!/bin/bash
# setup_actions.sh - Interactive setup script for action configuration
# This script helps configure webhook, email, and wazuh integrations

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"

echo "=========================================="
echo "  Action Configuration Setup"
echo "=========================================="
echo ""

# Function to ask yes/no question
ask_yes_no() {
    local prompt="$1"
    local default="${2:-n}"
    local answer
    
    if [ "$default" = "y" ]; then
        prompt="$prompt [Y/n]: "
    else
        prompt="$prompt [y/N]: "
    fi
    
    read -p "$prompt" answer
    answer="${answer:-$default}"
    
    if [[ "$answer" =~ ^[Yy]$ ]]; then
        return 0
    else
        return 1
    fi
}

# Function to ask for input
ask_input() {
    local prompt="$1"
    local default="$2"
    local var_name="$3"
    local answer
    
    if [ -n "$default" ]; then
        prompt="$prompt [$default]: "
    else
        prompt="$prompt: "
    fi
    
    read -p "$prompt" answer
    answer="${answer:-$default}"
    
    if [ -n "$answer" ]; then
        echo "$var_name=$answer" >> "$ENV_FILE"
        echo "✓ Added $var_name"
    fi
}

# Create or backup .env file
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env file already exists. Backing up to .env.backup"
    cp "$ENV_FILE" "$ENV_FILE.backup"
else
    touch "$ENV_FILE"
    echo "# Action Configuration - Generated by setup_actions.sh" >> "$ENV_FILE"
    echo "# Generated on: $(date)" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

echo ""
echo "This script will help you configure:"
echo "  1. Webhook integration (HTTP POST alerts)"
echo "  2. Email alerts (SMTP)"
echo "  3. Wazuh SIEM integration"
echo ""

# Webhook Configuration
echo "=========================================="
echo "  1. Webhook Configuration"
echo "=========================================="
if ask_yes_no "Configure webhook integration?"; then
    ask_input "Webhook URL (e.g., https://your-server.com/api/alerts)" "" "WEBHOOK_URL"
fi
echo ""

# Email Configuration
echo "=========================================="
echo "  2. Email Configuration"
echo "=========================================="
if ask_yes_no "Configure email alerts?"; then
    ask_input "SMTP Host" "smtp.gmail.com" "EMAIL_SMTP_HOST"
    ask_input "SMTP Port" "587" "EMAIL_SMTP_PORT"
    ask_input "SMTP Username" "" "EMAIL_USERNAME"
    ask_input "SMTP Password (use App Password for Gmail)" "" "EMAIL_PASSWORD"
    ask_input "From Email Address" "" "EMAIL_FROM"
    ask_input "To Email Address (recipient)" "" "EMAIL_TO"
    echo ""
    echo "ℹ️  Note: For Gmail, you need to use an App Password:"
    echo "   https://support.google.com/accounts/answer/185833"
fi
echo ""

# Wazuh Configuration
echo "=========================================="
echo "  3. Wazuh SIEM Configuration"
echo "=========================================="
if ask_yes_no "Configure Wazuh integration?"; then
    ask_input "Wazuh Manager Host" "" "WAZUH_MANAGER_HOST"
    ask_input "Wazuh Manager Port" "55000" "WAZUH_MANAGER_PORT"
    ask_input "Wazuh API URL (e.g., https://wazuh-manager:55000)" "" "WAZUH_API_URL"
    ask_input "Wazuh API Username" "wazuh" "WAZUH_API_USER"
    ask_input "Wazuh API Password" "" "WAZUH_API_PASSWORD"
    ask_input "Wazuh Socket Path (optional, leave empty for auto-detect)" "" "WAZUH_SOCKET_PATH"
    ask_input "Wazuh Method (auto/socket/api/log)" "auto" "WAZUH_METHOD"
fi
echo ""

echo "=========================================="
echo "  Configuration Complete!"
echo "=========================================="
echo ""
echo "Configuration saved to: $ENV_FILE"
echo ""
echo "To use these settings:"
echo ""
echo "  ✓ The .env file is automatically loaded by python-dotenv"
echo "    No need to manually source it (avoids conflicts with venv activation)"
echo ""
echo "  Just run the detection pipeline:"
echo "     python scripts/detection_pipeline.py --continuous \\"
echo "       --action alert --action webhook --action email --action wazuh"
echo ""
echo "  The script will automatically load variables from: $ENV_FILE"
echo ""

